# Generated by Django 4.2.17 on 2025-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='author',
            name='uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
